# Configurações do Banco de Dados (Supabase PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.eaeoghsqcdpfysekwdji.supabase.co:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:AD@84530392}

# Ajustes de Conexão para Nuvem (Mais robusto)
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.validation-timeout=3000
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Segurança JWT
nexus.jwt.secret=${JWT_SECRET:SUA_CHAVE_SECRETA_PADRAO_PARA_DESENVOLVIMENTO}
nexus.jwt.expiration=86400000

# Porta e Endereço do Servidor
server.port=${PORT:8081}
server.address=0.0.0.0
